In [1]:
import numpy as np

In [2]:
print(np.random.binomial(1,0.5,1))

[0]


In [3]:
print(np.random.binomial(5,0.5,10))

[3 3 3 0 1 2 3 3 1 2]


- The first argument represents the number of trials - or how many coin flips we’re doing in each experiment
- The second argument represents  or the probability of “success”.
- The third argument represents how many experiments you’re running

## Building the Experiment

In [2]:
for i in range(10):
    print(np.random.binomial(1,0.5,1))

[0]
[1]
[0]
[0]
[0]
[1]
[1]
[0]
[1]
[0]


**OR**

In [3]:
print(np.random.binomial(1,0.5,10))

[1 0 0 1 0 1 0 1 0 1]


In [4]:
print(np.random.binomial(20,0.5,10))

[ 8  5 11 12 10 11  9 11 10  4]


## REPEATED BERNOULLI EXPERIMENTS

In [5]:
np.random.seed(seed=7)
print(np.random.binomial(5,0.5,20))

[1 3 2 3 5 3 3 1 2 2 3 3 2 1 2 4 2 2 4 0]


In [7]:
n_1000 = np.random.binomial(5,0.5,1000)
n_10000 = np.random.binomial(5,0.5,10000)
n_100000 = np.random.binomial(5,0.5,100000)

print(f"probability for 1000: {np.sum(n_1000==4)/1000}")
print(f"probability for 100000: {np.sum(n_10000==4)/10000}")
print(f"probability for 1000000: {np.sum(n_100000==4)/100000}")

probability for 1000: 0.159
probability for 100000: 0.1632
probability for 1000000: 0.15635


## VISUALIZING FLIPPING A COIN

In [8]:
import matplotlib.pyplot as plt
import numpy as np
from ipywidgets import interact
np.random.seed(seed=7)

In [13]:
def bar_chart(flips):
    np.random.seed(seed=7)
    result = np.random.binomial(5,0.5,flips)
    fig = plt.figure()
    ax = plt.subplot(111)
    n,bins,patches = ax.hist(result, bins=np.arange(7)-0.5, rwidth=0.8, density=True)
    ax.set_xlabel('Number of Times Throwing Heads', size=16)
    ax.set_ylabel('Frequency', size=16)

In [14]:
interact(bar_chart, flips = [1,100,1000,10000,100000,1000000])

interactive(children=(Dropdown(description='flips', options=(1, 100, 1000, 10000, 100000, 1000000), value=1), …

<function __main__.bar_chart(flips)>

## Bernoulli experiments to model room bookings

In [21]:
def booking(amount):
    bookings = np.random.binomial(100,0.92,size=amount)
    length = len(np.unique(np.array(bookings)))
    
    fig = plt.figure()
    ax = fig.add_subplot(111)
    n,bins,patches = ax.hist(bookings, bins = np.arange(81,101)-0.5, rwidth=0.9,density=True)
    ax.set_xlabel('Number of rooms booked', size=16)
    ax.set_ylabel('Frequency', size=16)
    ax.set_xticks(range(82,100))
    plt.show();

In [22]:
interact(booking, amount=[1,100,1000,10000,100000,1000000])

interactive(children=(Dropdown(description='amount', options=(1, 100, 1000, 10000, 100000, 1000000), value=1),…

<function __main__.booking(amount)>

## CALCULATING PROFIT ON ANY GIVEN NIGHT

In [29]:
def num_booked(booking):
    booking_num = np.array(np.random.binomial(booking,0.92,10000))
    
    fig = plt.figure()
    ax = fig.add_subplot(111)
    ax.hist(booking_num, bins = np.arange(84,104)-0.5, rwidth=0.9, density=True)
    ax.set_xlabel('Number of rooms booked', size=16)
    ax.set_ylabel('Frequency', size=16)
    ax.set_xticks(range(85,booking))
    plt.show()

### 1) The Bernoulli Experiment when booking 104 rooms

In [30]:
interact(num_booked, booking = range(90,110))

interactive(children=(Dropdown(description='booking', options=(90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 10…

<function __main__.num_booked(booking)>

### 2) The Profit Distribution when booking 104 rooms

In [32]:
np.random.seed(seed=7)

booking_104 = np.random.binomial(104,0.92,10000)

booking_number = np.array(booking_104)

revenue = 200*booking_number
cost = 400*(booking_number-100)
cost_final = np.where(cost<0,0,cost)
profit = revenue - cost_final

print(profit)

[19800 18800 19200 ... 18600 19000 19600]


### 3) The Expected Profit

In [34]:
print(np.sum(profit)/10000)

19124.42


In [38]:
def num_booked(booking = 104):
    booking_num = np.array(np.random.binomial(booking,0.92,10000))
    
    fig = plt.figure()
    ax = fig.add_subplot(111)
    bins = np.arange(booking_num.min(),booking_num.max())
    
    ax.hist(booking_num, bins = bins-0.5, rwidth=0.9,density = True)
    
    n, bins, patches = ax.hist(booking_num, bins = bins-0.5, rwidth=0.9, density = True) 
    ax.set_xlabel(f"Expected occupancy with {booking} rooms booked", size=16)
    ax.set_ylabel('Frequency', size=16)
    ax.set_xticks(range(85,booking))
    plt.show()
    
                  
    booking_rooms= np.array(np.random.binomial(n=booking, p=0.92, size=10000))
    booking_number = np.array(booking_rooms)
    revenue = 220 * booking_number
    cost = (booking_number - 100) * 400
    cost_final = np.where(cost<0, 0, cost) 
    profit = revenue - cost_final
    
                  
    fig = plt.figure()
    ax = fig.add_subplot(111)
    bins2 = np.arange(profit.min(), profit.max(),(round((profit.max() - profit.min())/18)))
   
    n, bins, patches = ax.hist(profit, bins = bins2,  rwidth=0.9, density = True) 
    ax.set_xlabel(f"Expected profit when booking {booking} rooms", size=16)
    ax.set_ylabel('Frequency', size=16)
    plt.show()

In [39]:
widget = interact(num_booked, booking=[90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 
                                          104, 105, 106, 107, 108, 109])

interactive(children=(Dropdown(description='booking', index=14, options=(90, 91, 92, 93, 94, 95, 96, 97, 98, 9…